### ISSUE TITLE
Overview page about the Translator SmartAPI Registry, cross-linked to external resources and tutorials

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/translator-developer-documentation#12]
- [ ] [Registry overview page](https://github.com/NCATSTranslator/translator-developer-documentation/blob/main/docs/architecture/registry.md)

**Comment by tursynay** [comment]
@newgene, hi. We wanted to follow up with you regarding this issue. We are wondering if you would be able to work on this issue in the next couple of weeks. Please let us know if there is anyone else we should reach out to about this. Thank you.

**Comment by newgene** [comment]
@tursynay we are working on it...

**Comment by tursynay** [comment]
Thanks for the update, Chunlei.

**Comment by RichardBruskiewich** [comment]
Substantially resolved by PR #18
