### ISSUE TITLE
Elaborate introduction documentation for workflows and operations...

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/translator-developer-documentation#14]
Just putting a general issue post in the ground: this issue is already being resolved in PR issue https://github.com/NCATSTranslator/translator-developer-documentation/pull/5 - thank you David!

**Comment by tursynay** [comment]
@dkoslicki , hello. Thank you for the PR details. We wanted to follow up to see if it is close to merging. Thanks.

**Comment by RichardBruskiewich** [comment]
Resolved by PR #5
