### ISSUE TITLE
Provide an example for "Hello Translator” (Jupyter Notebook(s) making a TRAPI query?)

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/translator-developer-documentation#16]
@cbizon, please provide the examples here: 
https://github.com/NCATSTranslator/translator-developer-documentation/blob/main/docs/guide-for-developers/quickstart.md

**Comment by RichardBruskiewich** [comment]
Resolved by PR https://github.com/NCATSTranslator/translator-developer-documentation/pull/22
