### ISSUE TITLE
Move documentation from readthedocs to git hub pages

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/translator-developer-documentation#23]
... since NCATS Translator has a dedicated github.io domain for this... see SRI Testing or Reasoner-Validator for workflows and Github Settings to accomplish this.

Then, automate the publication of the documentation using a Git Action.

**Comment by vemonet** [comment]
@RichardBruskiewich I can give you a hand on this if you wish, I have done it for many documentation website and am quite familiar with the process now

**Comment by RichardBruskiewich** [comment]
Thanks @vemonet,  job done!
