### ISSUE TITLE
About page - remove Translator components and team names

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/translator-developer-documentation#27]
This issue is to suggest that Translator components (e.g., ARS) and team names are removed from the About page. This information is not relevant to developers and will only introduce confusion. DO keep the award/contract numbers, however.

**Comment by RichardBruskiewich** [comment]
Resolved by commit https://github.com/NCATSTranslator/translator-developer-documentation/commit/cab120badb2dcb3211df884aff7325594022a3f5
