### ISSUE TITLE
KP page - ask teams to add their KP information

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/translator-developer-documentation#28]
This issue is to suggest that you (or Tursynay) send a request to each KP primary owner to populate this page with their KP's information: https://translator-developer-documentation.readthedocs.io/en/latest/architecture/kp/.

**Comment by RichardBruskiewich** [comment]
OK, thanks for the recommendation Kara.

**Comment by RichardBruskiewich** [comment]
@karafecho, after looking again at the given page, I note that it has links to the Git repositories. I get the sense visiting those Git repositories, that each team is documenting their KP (or ARA) there, locally, probably thoroughly enough. This may suffice for now. Maybe Chris B.'s opinion on this might help.

**Comment by karafecho** [comment]
So, I see an incomplete list of Git repos? FWIW, Andy C. and I thought that we could point to the Translator wiki pages (see Exposures Providers entries for examples). We (Translator team members) are supposed to be keeping these pages up to date anyway. Thoughts?

**Comment by RichardBruskiewich** [comment]
A related issue #44 is created for follow up by the Biothings team with respect to the Service Provider KP wrapper.

**Comment by RichardBruskiewich** [comment]
> So, I see an incomplete list of Git repos? FWIW, Andy C. and I thought that we could point to the Translator wiki pages (see Exposures Providers entries for examples). We (Translator team members) are supposed to be keeping these pages up to date anyway. Thoughts?

I did a little bit of work on this some weeks ago. I guess the KP teams need to pick up the ball from here.

**Comment by karafecho** [comment]
I'm getting a 404 error when trying to access the link at the top of this issue. Assuming you are leveraging the wiki pages [here](https://github.com/NCATSTranslator/Translator-All/wiki), then yes, the KP teams should probably be responsible for keeping them up to date. Perhaps we should ping the contacts listed for each page, just to remind them?

**Comment by vemonet** [comment]
Hi @karafecho and @RichardBruskiewich wouldn't it make sense to have such information about the Team tools and services in one place? Otherwise it will be too hard to update for the teams, will  duplicate the documentation effort, and be confusing for the readers ("where do I find how to query this specific Team? Was it the wiki or the dev doc or else?")  

Imo it would make sense to migrate all the pages from the Translator-All/wiki to this website, so that all technical documentations on how to access the Translator infrastructure and its different components are available on this website, making it easier to find and update things 

It would be easy and fast to move all wiki pages here, then we would just need to announce to all teams that the new place to update their tools/services info is this repository

If we want to add more detailed instructions on how to use a team service or tool, then those could be added either in the README of the tool itself, or in the Team page 

What do you think?

**Comment by karafecho** [comment]
I agree that this is a good idea, @vemonet . However, we'd need to receive approval from NCATS, the UI team, and the Biolink team, as: NCATS 'owns' the Translator wiki pages and requested that teams use these to describe (in a user-friendly manner) team composition/role and components (separately from teams, but perhaps cross-linked); the UI team is using the wiki URLs to provide users with information on primary knowledge sources to aid in edge interpretation; and the Biolink team is housing those URLs in the InfoRes Catalog, which is being used as ground truth for the UI team to find the appropriate URLs.

Note that the process I'm describing here has evolved quite a bit from the intent of my original post back in March, which likely (but unfortunately) may have introduced some confusion and lack of coordination across team. (Apologies!)

@sstemann @Genomewide @sierra-moxon : What do you think?

**Comment by Genomewide** [comment]
By 'this website' do we mean the UI?

**Comment by Genomewide** [comment]
If it is not about how to use the UI, but is about the details of using the rest of the Translator tools, then I think it could be confusing to have that on the current UI.  I would prefer not to have that.

**Comment by karafecho** [comment]
I believe there are two issues here:

1. Whether the UI should include a link to the developer documentation. Andy and I suggest that we do not do that.
2. The second issue is whether the Translator wiki pages should be moved to the developer documentation. This is a decision that will need approval from NCATS, the UI team, and the Biolink team.

Hope this helps ...

**Comment by RichardBruskiewich** [comment]
In the world of basic science, links to the more technical aspects of a (bio)informatic resource would make sense, but this is not a typical basic science resource, so yes... no direct link to developer docs. Of course, as part of future sustainability and outreach of the project, NCATS should likely host a suitable landing page at their end that points interested technical parties to the details under the hood, including the tech docs, etc.

**Comment by karafecho** [comment]
So, it sounds like folks agree to leave things as is for now, with NCATS hosting the wiki pages and the UI including links to scientific publications, blogs, etc, but NOT the developer documentation.

Closing this ticket and opening another one to suggest a solution for the developer documentation that I think will address the initial suggestion put forward by @vemonet without changing the way we are managing wiki pages, displaying content on the UI, etc.
