### ISSUE TITLE
Link to a rendered version of the “Hello Translator” Jupyter Notebook

### ISSUE THREAD

**Issue by andrewsu** [NCATSTranslator/translator-developer-documentation#34]
We currently have links to a [“Hello Translator” Jupyter Notebook](https://translator-developer-documentation.readthedocs.io/en/latest/guide-for-developers/HelloTranslator.ipynb) that, when clicked, downloads the notebook to my local computer.  I think we should update this link to point to a _rendered_ version of the notebook.  For example, either of these links would be better I think:
* https://github.com/NCATSTranslator/translator-developer-documentation/blob/main/docs/guide-for-developers/HelloTranslator.ipynb
* https://colab.research.google.com/github/NCATSTranslator/translator-developer-documentation/blob/main/docs/guide-for-developers/HelloTranslator.ipynb

**Comment by RichardBruskiewich** [comment]
Fully resolved by commit https://github.com/NCATSTranslator/translator-developer-documentation/commit/14fcccac569c2b74903cb0dddb1bb342be27223f
