### ISSUE TITLE
Service Provider documentation

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/translator-developer-documentation#44]
Service Provider is a general wrapper for third party resources, making them TRAPI endpoints. It would be helpful to fully document this useful technology for future Translator developers.

There is a stub page at https://github.com/NCATSTranslator/translator-developer-documentation/blob/master/docs/architecture/kp/service_provider.md to which a suitable PR may be prepared to the Translator Technical Documentation.

**Comment by andrewsu** [comment]
I'm going to unassign Colleen for the moment and assign to me and @newgene. Would just like to prioritize this relative to other tasks and team members.

**Comment by RichardBruskiewich** [comment]
Sure @andrewsu that's fine. It was just that Colleen appeared to be taking ownership for so much of the project work on your side, hence I channelled the task through her. To reiterate, what is probably only needed here is a 'landing' page overview of the functionality of the Service Provider component with links out to available online documentation elsewhere, as an entry point for new developers.

**Comment by RichardBruskiewich** [comment]
Substantially resolved by PR https://github.com/NCATSTranslator/translator-developer-documentation/pull/45
