### ISSUE TITLE
Improving the documentation style

### ISSUE THREAD

**Issue by vemonet** [NCATSTranslator/translator-developer-documentation#46]
Do we want to continue using the style from readthedocs?

I know a lot of people are used to it

Personally I find it not user friendly at all, mainly because the screen space is really poorly handled

On my small laptop 14" screen more than half of the screen is wasted in a blank page without any reason, and it is not even centered! 

![Screenshot from 2023-09-22 15-37-27](https://github.com/NCATSTranslator/translator-developer-documentation/assets/3778439/5cc86267-45e7-4c62-9829-5cb7dd66b3e9)

It is probably true for most people, and even worse on bigger screens

Also it lacks a lot of really useful features:
* Table of Contents within each page
* Light/dark mode (mandatory in 2023, especially for devs!)

To improve this I would propose to migrate to [**Material for Mkdocs**](https://squidfunk.github.io/mkdocs-material/), which is more modern, with a lot of cool features, used and supported by many projects. E.g. https://fastapi.tiangolo.com 

The migration would be really easy to perform, since the website already uses mkdocs

And there are some features that would be super useful in the context of the Translator, such as adding a userf-friendly glossary of terms and abbreviations (very much needed so that we can use our beloved abbreviations everywhere and everyone will still be able to understand them!)

I already have a good experience building documentation websites with this tool, so if folks are ok with it I could make all the changes required, adding some new cool features and send a PR @RichardBruskiewich

**Comment by RichardBruskiewich** [comment]
Resolved by https://github.com/NCATSTranslator/translator-developer-documentation/pull/47 and subsequent tweaks to master. Done!
